- .reek.yml
> Removed redudant slash in the end of path to exclude

- app/models/user.rb
- db/migrate/20190806120054_create_users.rb
- db/schema.rb
Create User model
[card](https://trello.com/c/sZ3geX3v)
> DEV005 create model user

- app/models/genre.rb
- app/models/user.rb
- app/models/user_genre.rb
- db/migrate/20190806120303_create_genres.rb
- db/migrate/20190806123322_create_user_genres.rb
- db/migrate/20190807131852_change_users_table.rb
- db/schema.rb
Create model genre
[card](https://trello.com/c/M8Al1Lq8)
> DEV006 create model genre

- app/models/image.rb
- app/models/place.rb
- app/models/user.rb
- db/migrate/20190807133747_create_images.rb
- db/schema.rb
- spec/models/image_spec.rb
Create model Image
[card](https://trello.com/c/RsdFBKQB/31-dev002-create-model-image)
> DEV002 Create model Image 

- app/models/moderator.rb
DEV016 Add moderator model
[card](https://trello.com/c/azn3EQkh)
> DEV016 Add moderator model

- app/models/event.rb
- app/models/musician_skill.rb
- app/models/musician_skill_user.rb
- app/models/user.rb
- db/migrate/20190807133747_create_images.rb
- db/migrate/20190808073147_create_musician_skill_users.rb
- db/migrate/20190808073217_create_musician_skills.rb
- db/migrate/20190808171446_rename_images_table_columns.rb
- db/schema.rb
- db/seeds.rb
Create model MusicianSkill
[card](https://trello.com/c/ra8YFKG2/46-dev004-create-model-musicianskill)
> DEV004 Create model MusicianSkill

- app/models/event.rb
- app/models/organization.rb
- app/models/organization_event.rb
- app/models/user.rb
- app/models/user_organization.rb
- db/migrate/20190807123945_create_organizations.rb
- db/migrate/20190807124635_create_organization_events.rb
- db/migrate/20190807124812_create_user_organizations.rb
- db/schema.rb
Create model organizations
[card](https://trello.com/c/BfkD5Q5I)
> DEV007 create model organizations

- app/controllers/api/genres_controller.rb
- app/serializers/genre_serializer.rb
- config/routes.rb
- spec/controllers/genres_controller_spec.rb
Create controller for genres model
[card](https://trello.com/c/0cvm8aUa)
> DEV011 Create controller for genres model

- app/models/user.rb
- db/migrate/20190809111639_add_status_to_musician_skill_users.rb
- db/schema.rb
Add migration to add column status to musician_skill_users, fix musician_skill_users.status
[card](https://trello.com/c/1umItyZ0)
> BUG008 fix musician skill users.status

- app/models/event.rb
- app/serializers/event_serializer.rb
Rename fields in model and serializer
[card](https://trello.com/c/Xvg0q7q6)
> BUG009 fix pending events organisations relation

- package.json
- yarn.lock
DEV032 Setup material ui
[card](https://trello.com/c/93g7ObpW)
> DEV032 Setup material ui

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/events_controller.rb
- app/controllers/genres_controller.rb
- app/controllers/musician_skills_controller.rb
- app/controllers/organizations_controller.rb
- app/controllers/places_controller.rb
- app/controllers/users_controller.rb
- app/models/ability.rb
- app/models/event.rb
- app/models/guest.rb
- app/models/user.rb
Card - [DEV017 Setup Cancancan](https://trello.com/c/hTJjkPtF) 
Add gem cancancan
Add ability model
Add authorize for all controllers
Add has_many to users in event model
> DEV017 Setup Cancancan

- app/javascript/packs/application.js
- app/views/layouts/application.html.erb
[card](https://trello.com/c/J9pHHXGM)
Fix conflicts with stylesheet for matrerial ui and activeadmin
> DEV044 Fix conflicts with cativeadmin styles and matrial-ui

- app/assets/javascripts/components/shared/landingPage.jsx
- app/javascript/components/shared/navigation/navigation.jsx
- app/views/layouts/application.html.erb
Fix frame and nigation
[card](https://trello.com/c/cAbp2gts)
> BUG010 fix frame and navbar

- Gemfile
- Gemfile.lock
- app/javascript/packs/application.js
- config/initializers/assets.rb
[card](https://trello.com/c/R3wq30UX)
> BUG011 asset not precompiled

- db/seeds.rb
Add images for place model
[card](https://trello.com/c/9g3Exwtp/88-bug015-add-images-for-place-model)
> BUG015 Add images for place model

- db/seeds.rb
Add confirm
[card](https://trello.com/c/CAnRdPbs/91-bug017-fix-seeds-for-image)
> BUG017 Fix seeds for image

- app/controllers/application_controller.rb
- app/models/ability.rb
Change redirect derictory, and add abbility for change self user model
[card](https://trello.com/c/V4c90Ijp)
> BUG018 Fix cancancan

- app/views/layouts/application.html.erb
change send props in navigation
[card](https://trello.com/c/LYT8Hxvm)
> BUG017 Fix current_user image in navigation

- app/javascript/components/organizations/organization_title.jsx
- app/views/layouts/application.html.erb
[card](https://trello.com/c/lgTdh0Yp)
> BUG019 Fix application.html.erb

- app/controllers/application_controller.rb
- app/controllers/events_controller.rb
- app/controllers/organizations_controller.rb
- app/controllers/places_controller.rb
- app/controllers/users_controller.rb
- app/controllers/welcome_controller.rb
- app/javascript/components/places/PlaceShow.jsx
- app/javascript/components/welcome/WelcomePage.jsx
- app/javascript/components/welcome/stepper.jsx
- app/serializers/event_serializer.rb
- app/views/welcome/page.html.erb
- config/routes.rb
Create welcome page
[card](https://trello.com/c/zyPNk7kx/90-dev046-create-main-page)
> DEV046 Create welcome page

- app/controllers/moderators_controller.rb
- config/routes.rb
Moderator cant edit himself
[card](https://trello.com/c/ZjQcqq31)
> BUG020 moderator cant edit himself

- app/controllers/application_controller.rb
- config/initializers/active_admin.rb
Create new method to redirect to root path without error message
[card](https://trello.com/c/z05XKeeh)
> DEV054 Add redirect to welcome page  when user hasn't rules(activeadmin)

- app/javascript/components/events/event_index.jsx
- app/javascript/components/events/event_show.jsx
- app/javascript/components/organizations/organization_detail.jsx
- app/javascript/components/organizations/organization_index.jsx
- app/javascript/components/organizations/organization_title.jsx
- app/javascript/components/organizations/organization_title_name.jsx
- app/javascript/components/places/PlaceIndex.jsx
- app/javascript/components/places/PlaceShow.jsx
- app/javascript/components/users/user_index.jsx
- app/javascript/components/users/user_show.jsx
- app/javascript/components/welcome/WelcomePage.jsx
Fix frame for react components
[card](https://trello.com/c/nGfTagV6)
> DEV048 fix frame for react components

- app/javascript/components/shared/yandex_maps.jsx
- package.json
- yarn.lock
CARD: [DEV049_create yandex_maps_component](https://trello.com/c/IHZ8WzHB)
> DEV049_create yandex_maps_component

- app/javascript/components/shared/navigation/navigation.jsx
Add button with links
[card](https://trello.com/c/R9H3dTRV/98-dev051-add-to-header-links)
> DEV051 Add to header links

- app/javascript/components/organizations/organization_detail.jsx
- app/javascript/components/organizations/organization_title.jsx
- app/javascript/components/organizations/organization_title_name.jsx
- app/views/devise/confirmations/new.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/layouts/application.html.erb
Add css styles to device pages
[card](https://trello.com/c/iUXgXQcc)
> DEV052 add css styles to device pages

- app/controllers/users_controller.rb
- app/views/users/edit.html.erb
[card](https://trello.com/c/xyIlfZgj)
> BUG023 duplicate in select

- app/controllers/users_controller.rb
- app/javascript/components/users/user_show.jsx
Add genre in user show
[card](https://trello.com/c/fRFRlctF)
> BUG022 add genre in user show

- app/assets/javascripts/organizations/edit.js
- app/assets/javascripts/organizations/new.js
- app/controllers/organizations_controller.rb
- app/services/image_service.rb
- app/views/organizations/edit.html.erb
- app/views/organizations/new.html.erb
Created jquery script to multi prerender image
[card](https://trello.com/c/nBWuWUwd)
> DEV064 Add multiadd image

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/javascript/components/organizations/organization_card.jsx
- app/javascript/components/shared/button.jsx
- app/javascript/components/shared/button_event.jsx
- app/javascript/components/shared/card_event.jsx
- app/javascript/components/shared/card_events.jsx
- app/javascript/components/shared/card_places.jsx
- app/javascript/components/shared/navigation/navigation.jsx
- app/javascript/components/shared/navigation/navigation_button.jsx
- app/javascript/components/users/user_card.jsx
Fix turbolink
[card](https://trello.com/c/nIzhr1ca)
> BUG025 fix turbolink

- app/assets/javascripts/organizations/edit.js
- app/assets/javascripts/organizations/new.js
- app/controllers/organizations_controller.rb
- app/services/organization_delete_images_service.rb
- app/views/organizations/edit.html.erb
[card](https://trello.com/c/Gf21YKrj)
> DEV058 edit gallery

- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/users/edit.html.erb
Add ability to user(ban)
[card](https://trello.com/c/zim82hAw)
> DEV057 add ability to user(ban)

- app/assets/javascripts/active_admin.js
- config/initializers/active_admin.rb
[card](https://trello.com/c/vZux2xb4)
> BUG021 Fix button log out in activeadmin header

- app/admin/users.rb
- app/models/user.rb
[card](https://trello.com/c/D9BFPyJp)
> DEV070 Add ability to ban user in active admin

- app/controllers/organizations_controller.rb
- app/mailers/user_mailer.rb
- app/services/organization_delete_users.rb
- app/services/organization_invite_users.rb
- app/views/organizations/edit.html.erb
- app/views/user_mailer/delete_email.html.erb
- app/views/user_mailer/invite_email.html.erb
- config/routes.rb
[card](https://trello.com/c/EofXhGMJ)
> DEV056 Invite user to organization

- app/services/user_service.rb
Fix add photo in user
[card](https://trello.com/c/yQtCnSPK)
> BUG26 fix add photo in user

- Gemfile.lock
- app/javascript/components/organizations/organization_card.jsx
- app/javascript/components/shared/event_card.jsx
- app/javascript/components/shared/place_card.jsx
- app/javascript/components/users/user_card.jsx
[card](BUG013 Fix component "CARD")
> BUG013 fix component card

- README.md
Add Readme
[card](https://trello.com/c/7PxIAUOv)
> DEV73 Add Readme

- app/admin/places.rb
Add ability to add place's photo in admin menu
[card](https://trello.com/c/FbIEuXOW)
> DEV073 Add add photo in admin

- app/controllers/organizations_controller.rb
- app/helpers/organization_helper.rb
- app/javascript/components/organizations/organization_detail.jsx
- app/javascript/components/organizations/organization_title.jsx
- app/javascript/components/shared/navigation/dialog_window.jsx
- app/javascript/components/users/user_show.jsx
- app/javascript/components/welcome/welcome_page.jsx
- app/models/organization.rb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/events/index.html.erb
- app/views/organizations/new.html.erb
- app/views/organizations/show.html.erb
- config/routes.rb
- db/migrate/20190830131602_add_group_to_organizations.rb
- db/schema.rb
- db/seeds.rb
Add logic at choose place
[card](https://trello.com/c/qzzE2GTT)
> DEV066 add logic at choose place
